name: E2E

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16] # Dosn't work with 18. https://github.com/cypress-io/github-action/issues/534#issuecomment-1115947632
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: pnpm run dev
          command: pnpm run cy
          wait-on: http://127.0.0.1:8080
      - name: Upload artifacts  # Find artifacts under actions/jobs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: snapshots
          path: ./cypress/
